### PR TITLE
Only for debugging

### PR DESCRIPTION
**Pull request by andesol**
Important: this won't save the changes in Greenhouse. It will go through the applications as usual but it'll click "Close" instead of "Save".

## Steps

- Checkout this branch
- Check that you have `ght-graders.yml` in your home directory
- Run 
```
yarn dev assign -i
```
- Select the jobs
- Let the app run and share the console output with me

Thanks!

### CODE REVIEW

**Comment by anthonydillon** [comment]
I get this error:
```
$ NODE_ENV=development ts-node ./src/index.ts assign -i
/home/ant/projects/ght/src/automations/Job.ts:38
        if (!protectedPosts?.length) {
                            ^

SyntaxError: Unexpected token '.'
```

**Comment by andesol** [comment]
@anthonydillon What I definitely didn't expect was a compilation error...

What node version are you using? Anything >14 should be fine with this syntax

**Comment by anthonydillon** [comment]
Your right, my bad

**Comment by anthonydillon** [comment]
Works perfectly :+1:

**Comment by andesol** [comment]
Closing this for now, we can reopen it again if needed

**Pull request closed without merging**
