### PR TITLE
Add several more cities in Canada, Latin America and Middle East

### PR DESCRIPTION
**Pull request by camille-rodriguez**
Some roles require hiring in Canada, Latin America and Middle East for specific business reasons and having those options spelled out makes the hiring lead job much easier. The EMEA region only had 1 city listed in Middle East.

### CODE REVIEW

**Comment by camille-rodriguez** [comment]
@anthonydillon if you could please review, thank you!

**Comment by anthonydillon** [comment]
@camille-rodriguez Thanks this is nice work. I have added a little defence for duplicated cities if a sub-region is selected with the major region. Also added tests and project documentation for the new regions.

**Review by anthonydillon — APPROVED** [review]
LGTM :+1:

**Comment by camille-rodriguez** [comment]
Thank you for the quick review & update!

**Pull request merged**
