### PR TITLE
Bump minor version to 1.7.1

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done

- Bumped both versions to 1.7.1

### CODE REVIEW

**Review by andesol — APPROVED** [review]

**Comment by andesol** [comment]
@anthonydillon Is the change on the package-lock intended?

**Comment by anthonydillon** [comment]
I was trying to get the new check to pass. @jnsgruk any idea what is causing the error? Seems to be in the diff command.

Happy to revert the lock change.

**Comment by jnsgruk** [comment]
So I'd expect there to be a change because the package version has changed -- what happens if you `npm i --package-lock-only` and commit the changes?

**Comment by jnsgruk** [comment]
Was chatting with @anthonydillon about this -- we think it's due to mismatched node/npm versions. I opened #230 which shows a more minimal diff with the checks passing.

**Comment by anthonydillon** [comment]
Superseded by https://github.com/canonical/ght/pull/230

**Pull request closed without merging**
